Fix previous commit
Hopefully this one fixes a privately reported regression introduced
with the previous commit.

```python
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'
```